spring.application.name=TiendaNattScholz

# Puerto donde se ejecuta el servidor
server.port=8080

# Formato de hora en los mensajes de consola
logging.pattern.dateformat=hh:mm

# Oculta el banner de Spring al iniciar
spring.main.banner-mode=off

# Desactiva el cache de Thymeleaf en desarrollo
spring.thymeleaf.cache=false